---
- name: Initialize Kubernetes cluster on master node
  hosts: k8s_master
  become: yes
  vars:
    k8s_version: "1.30.0"
    pod_network_cidr: "10.244.0.0/16"
    k8s_admin_user: "dchernyshov"
    k8s_admin_home: "/home/dchernyshov"

  tasks:
    # --- БЛОК ОЧИСТКИ ---
    
    - name: Check if cluster is already running
      stat:
        path: /etc/kubernetes/admin.conf
      register: k8s_conf

    # Важно: если IP был неправильный, лучше сбросить кластер принудительно
    # Если вы уверены, что хотите пересоздать кластер, можно раскомментировать строку ниже временно:
    # - shell: kubeadm reset -f

    - name: Reset partially initialized cluster
      shell: |
        kubeadm reset -f
        rm -rf /etc/kubernetes/pki
        rm -rf /var/lib/etcd
      when: not k8s_conf.stat.exists
      ignore_errors: yes

    # -----------------------------

    - name: Initialize cluster with kubeadm
      shell: |
        kubeadm init \
          --pod-network-cidr {{ pod_network_cidr }} \
          --service-cidr 10.96.0.0/12 \
          --kubernetes-version v{{ k8s_version }} \
          --apiserver-advertise-address 192.168.1.11 \
          --apiserver-cert-extra-sans {{ ansible_hostname }}
      register: kubeadm_init
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Ensure .kube directory exists for admin user
      file:
        path: "{{ k8s_admin_home }}/.kube"
        state: directory
        owner: "{{ k8s_admin_user }}"
        group: "{{ k8s_admin_user }}"
        mode: 0755

    - name: Copy admin config to user directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ k8s_admin_home }}/.kube/config"
        remote_src: yes
        owner: "{{ k8s_admin_user }}"
        group: "{{ k8s_admin_user }}"
        mode: 0600

    - name: Generate fresh join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Save join command to file
      copy:
        content: "{{ join_command_raw.stdout }}"
        dest: /tmp/k8s_join_command.txt
        owner: "{{ k8s_admin_user }}"
        group: "{{ k8s_admin_user }}"
        mode: 0644

    - name: Display join command for verification
      debug:
        msg: "Join command: {{ join_command_raw.stdout }}"

    - name: Wait for Kubernetes API to be ready
      wait_for:
        host: "192.168.1.11"
        port: 6443
        delay: 10
        timeout: 300
