---
- name: Setup kubectl access on ansible control node
  hosts: k8s_master
  become: yes
  vars:
    # ИСПРАВЛЕНИЕ 1: Ваш реальный пользователь
    remote_user_home: "/home/dchernyshov"
    # ИСПРАВЛЕНИЕ 2: Используем /tmp, чтобы не просило sudo в контейнере
    local_home: "/tmp" 
    local_bin: "/tmp"

  tasks:
    - name: Fetch kubeconfig from Master
      fetch:
        src: "{{ remote_user_home }}/.kube/config"
        dest: "{{ local_home }}/kubeconfig"
        flat: yes

    # Мы убрали скачивание бинарника kubectl, так как в контейнере он уже есть или не нужен, 
    # а скачивание 50Мб каждый раз забивает память.
    
    - name: Verify we got the file
      stat:
        path: "{{ local_home }}/kubeconfig"
      delegate_to: localhost
      become: no
      # ИСПРАВЛЕНИЕ 3: Жестко запрещаем sudo для локальных действий
      vars:
        ansible_become: false 

    - name: Display success message
      debug:
        msg: "Config downloaded successfully to {{ local_home }}/kubeconfig"
